baseurl = "http://d7et.dicse.re/doc/"
languageCode = "en-us"
title = "D7ET Programming Lessons"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    	# information about you and your website.
	description = "Dublin 7 Educate Together Programming Lessons"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "D7ET Programming Lessons"

		[params.navigation.links]
			about     = "About"
			lessons   = "Lessons"
			contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Learn to program after school!"
		subtitle   = "Dublin 7 Educate Together National School is now offering advanced programming lessons for pupils as an afterschool activity"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Build a fun game for the web"
		description = "Since 2013, parent volunteers have been offering computer programming as an afterschool activity. The lessons are available to 4th class pupils, or higher,  and emphasise learning as fun and an opportunity for creativity. This initiative has successfully led to the introduction of Scratch and Sctatch Jnr programming into the main class curriculum for all pupils at the school since 2015. For the Spring 2016 term, students will learn how to build a fun game for the web over a series of weeks."
		buttonText  = "What can I learn?"


	# Lessons section
	[params.lessons]
             headline = "Weekly worksheets"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson one"
            description = "Introduction to the course content and the tools and technologies you will learn how to use"
	    link = "ProgrammingfortheWeb-Week1.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson two"
            description = "Continue building the game by setting up the main elements using HTML and Javascript drawing primitives"
	    link = "ProgrammingfortheWeb-Week2.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson three"
            description = "Refactoring the Javascript code and building out more game logic for our Tamagotchi!"
	    link = "ProgrammingfortheWeb-Week4.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson four"
            description = "If we don't think about how to feed our alien soon, we risk an untimely demise. In this lesson we find out how to give it bread"
	    link = "ProgrammingfortheWeb-Week5.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson five"
            description = "A diet of just bread will get boring very quickly. In this lesson we find out how to give it some treats and model how it gets hungry if we don't feed our alien"
	    link = "ProgrammingfortheWeb-Week8.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson six"
            description = "In this lesson we link feeding and hungriness to healthiness and what will keep our alien alive"
	    link = "ProgrammingfortheWeb-Week9.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson seven"
            description = "In this lesson we model how our alien gets older and the game play progresses"
	    link = "ProgrammingfortheWeb-Week10.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson eight"
            description = "As we give our alien sweets, we notice that it throws the wrappers on the ground. In this lesson we deal with counting and cleaning up"
	    link = "ProgrammingfortheWeb-Week11.pdf"

        [[params.lessons.list]]
            icon = "fa-file"
            title = "Lesson nine"
            description = "In this, the final lesson, we add some sound effects to the game play and find out that our alien is a very noisy eater"
	    link = "ProgrammingfortheWeb-Week12.pdf"

    # Aside section
	[params.aside]
		headline = "Look what we've achieved!"

		[params.aside.button]
			text = "Let's code!"
			link = "//d7et.disce.re/jsbin"

	# Contact section
	[params.contact]
		headline = "Need more information?"
		description = "Contact us through the school and we will get back to you as soon as possible!"
